import path from "node:path"
import { fileURLToPath } from "node:url"

const root = path.dirname(fileURLToPath(import.meta.url))

/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    // Static WebP variants generated by scripts/build-images.mjs.
    loader: "custom",
    loaderFile: "./lib/image-loader.ts",
    deviceSizes: [640, 828, 1080, 1440, 1920],
    imageSizes: [256, 384],
  },
  reactStrictMode: true,
  outputFileTracingRoot: root,
}

export default nextConfig
