/* ------------------------------------------------------------------
   COPY — every visible string of the home page and the briefing, in
   English and French. The French object must mirror the English one.
   ------------------------------------------------------------------ */

import type { ContractSlug } from "@/lib/contracts"
import type { Locale } from "@/lib/i18n"
import { PROJECT_STORIES, type HomeSectionId, type ProjectStory, type StorySlug } from "@/lib/journey"
import { DEPLOYMENTS, type Deployment } from "@/lib/profile"

type ContractOverride = { title?: string; role?: string; summary?: string; metricLabel?: string }

const en = {
  sections: {
    hero: "Start",
    contracts: "Selected work",
    origin: "My story",
    operator: "My approach",
    log: "Experience",
    extraction: "Contact",
  } as Record<HomeSectionId, string>,

  nav: {
    skip: "Skip to content",
    home: "Home",
    tagline: "// Event management",
    briefingShort: "30-sec briefing",
    briefingLong: "30-second briefing",
    sections: "Sections",
    sectionIndex: "Section index",
    storyNav: "Story navigation",
    openMenu: "Open navigation",
    closeMenu: "Close navigation",
    switchTo: { label: "Version française", short: "FR", lang: "fr" },
  },

  hero: {
    kicker: "A player's perspective",
    portfolio: "Jules Moreau / Portfolio 2026",
    availability: "Open to an internship",
    window: "FEB — JUN 2027",
    role: "Event management",
    title: ["Make sport", "happen."],
    specialty: "Event operations. Communication. Partnerships.",
    intro: "Hands-on experience on the ground, behind the content and alongside club partners. M2 International Sport Administration student, based in Lille and mobile across Europe.",
    explore: "Explore my work",
    talk: "Let's talk",
    briefing: "Short on time? Read the 30-second briefing",
    stamp: ["FROM PLAYING", "TO MAKING IT HAPPEN."],
    edge: "ON THE GROUND / BEHIND THE GAME",
  },

  work: {
    chapter: "01 / Selected work",
    chapterRight: "Three projects / Practical experience",
    title: ["Less theory.", "More impact."],
    introLabel: "On the ground. In the work.",
    intro: "Running a tournament. Giving a club a voice. Equipping a team for its next season. Three projects, three ways to make sport happen.",
    languageNote: "",
    scene: { featured: "Featured case", signal: "Content in action", field: "On the ground" },
    preview: "Royal Daring / Partner website",
    delivery: "Website · Brand · Brochure",
    alts: {
      daringSite: "Bilingual Royal Daring partner website designed and delivered by Jules",
      daringPacks: "Partner packages on the delivered Royal Daring website",
      signalPhoto: "ASN95 youth players photographed for club and sponsor communication",
      signalPoster: "ASN95 match poster created by Jules",
      field: "ASI university tournament on the ground in Lille",
    },
    featuredProof: ["Bilingual website.", "A complete partner system."],
    openFeatured: "Inside the partner system",
    open: "Explore the case study",
    archiveTitle: "More projects / Digital, strategy & photography",
    archiveCount: "04 projects",
    archive: {
      strategy: "Understanding the business behind esports.",
      "intel-core": "Turning daily information into a useful intelligence tool.",
      build: "Building websites for real organisations.",
      imagery: "Capturing the people and moments behind the event.",
    } as Partial<Record<ContractSlug, string>>,
    titles: {} as Partial<Record<ContractSlug, string>>,
    stories: PROJECT_STORIES as Record<StorySlug, ProjectStory>,
  },

  story: {
    chapter: "02 / The person behind the work",
    chapterRight: "Competition → Coaching → Event management",
    title: ["A player's", "perspective."],
    body: [
      "Competitive gaming made me curious about everything around the match: the people, the preparation and the experience.",
      "Coaching volleyball brought that curiosity onto the court. At a well-organised U13 tournament, I could focus on my team because the details had already been taken care of.",
    ],
    takeawayLabel: "What stayed with me",
    takeaway: ["Prepare the details.", "Let the game happen."],
    gamesLink: "Beyond the work / My gaming story",
    photoAlt: "Volleyball match photographed by Jules Moreau",
    photoTag: "My photography / LISSP Calais",
    caption: "Personal photography archive · Volleyball",
    highlights: "Watch my competitive gaming highlights",
    video: {
      header: "Competitive roots",
      play: "Play CS2 highlights",
      pause: "Pause CS2 highlights",
      caption: ["My plays. My perspective.", "CS2 / My highlights"],
    },
    places: {
      kicker: "Before the work / Where I grew up",
      count: "8 moves / 4 continents",
      title: ["Four continents.", "One habit: adapt."],
      intro: "I grew up moving with my family. Each place left me something I still use.",
      stops: [
        { place: "France", lesson: "The start", text: "Born here. Twenty-four days later, passport in hand, off to French Guiana." },
        { place: "French Guiana", lesson: "Nature", text: "Growing up close to nature, and to the golden-handed tamarins on our balcony." },
        { place: "Corsica", lesson: "Trail running", text: "Where trail running started for me." },
        { place: "New Caledonia", lesson: "The ocean", text: "Surfing and va'a, the outrigger canoe." },
        { place: "Congo · Brazzaville", lesson: "Perspective", text: "Realising how lucky I was." },
        { place: "France", lesson: "Back home", text: "A first return." },
        { place: "French Guiana", lesson: "Games", text: "Minecraft, then Counter-Strike, then Overwatch." },
        { place: "France", lesson: "Sport", text: "Studies, volleyball, golf and competitive gaming. Then sport management." },
      ],
    },
  },

  approach: {
    chapter: "03 / How I work",
    chapterRight: "Sport management · Field experience · Curiosity",
    title: ["One direction.", "Different skills."],
    body: "My path brings together competition, coaching, military discipline and creative work. They all feed the way I approach a project.",
    languages: ["French / Native", "English / C1", "FR · BE · Europe"],
    methods: [
      { title: "Prepare the ground.", text: "Coaching, event infrastructure work and the Navy Reserve taught me to take preparation, coordination and responsibility seriously." },
      { title: "Connect the people.", text: "Clear information for a team. Content that brings a club to life. Partnerships that give a project the resources to grow." },
      { title: "Build what is useful.", text: "Photography, websites and AI-assisted tools expand what I can deliver. I learn the tools a project needs, then put them to work." },
    ],
    tools: ["Tools, when they help", "Canva · Lightroom · Premiere", "Notion · Web · AI workflows"],
  },

  experience: {
    chapter: "04 / Experience & education",
    chapterRight: "Lille · Brussels · French Guiana",
    title: "On the ground.",
    cv: "Full CV / PDF",
    intro: "Practical experience with the people, equipment and preparation behind an event.",
    field: [
      { label: "Festival infrastructure / AUG 2025", title: ["Kourou Beach Festival", "& Tour de Guyane"], text: "Built the VIP hospitality complex and deployed sponsor arches with Bolt Echafaudage, under strict timing constraints." },
      { label: "Team logistics / 2024 — 2025", title: ["From training", "to tournament day"], text: "Organised transport and accommodation for the Ensisheim volleyball tournament alongside my coaching responsibilities at LISSP Calais." },
      { label: "Teamwork / SINCE 2022", title: ["Preparation.", "Responsibility."], text: "French Navy Reserve service taught me discipline, organisation and team leadership under pressure." },
    ],
    education: [
      { label: "2025 — 2027 / Université de Lille", title: "Master’s · International Sport Administration", text: "Sport management, governance and esports." },
      { label: "2022 — 2025 / ULCO", title: "Bachelor’s · Sport Management", text: "The academic foundation behind my field experience." },
    ],
    allRoles: "Explore all experience",
    roles: "roles",
    deployments: DEPLOYMENTS as Deployment[],
    personal: "Competition and creativity are still part of my everyday life.",
    gamesLink: "Beyond the projects / My gaming story",
  },

  contact: {
    chapter: "05 / Let's work together",
    chapterRight: "Event management internship / FEB — JUN 2027",
    title: ["Let's make", "it happen."],
    copy: "Need support with event logistics, communication or partner activation? I am looking for an event management internship where I can contribute on the ground.",
    copyStrong: "February to June 2027, in France, Belgium or elsewhere in Europe.",
    cv: "Download CV",
    briefing: "30-second briefing",
    meta: ["Lille / France", "FR native · EN C1"],
  },

  footer: {
    line: ["Jules Moreau / From playing to making it happen.", "Built with curiosity, field experience and AI-assisted tools."],
    label: "Footer",
    story: "My story",
    projects: "Projects",
    briefing: "Briefing",
    top: "Back to top ↑",
    marquee: ["PLAY", "UNDERSTAND", "MAKE IT HAPPEN"],
  },

  intro: {
    title: "Jules Moreau — Welcome to my world",
    description: "Sport, projects and games coming together. You can skip this short introduction.",
    topline: "Sport. Play. Create.",
    kicker: "A player's perspective",
    note: "A world of my own.",
    coordinates: "Always in motion.",
    phases: { drift: "A few things that make me.", gather: "All coming together.", dive: "Welcome in." },
    skip: "Skip intro",
    labels: {} as Record<string, string>,
  },

  briefing: {
    meta: {
      title: "Event Management internship · February–June 2027",
      description: "Jules Moreau is seeking an Event Management internship from February to June 2027. Experience in field operations, event logistics, club communication and sponsor activation.",
      ogTitle: "Jules Moreau · Event Management internship",
      ogDescription: "February–June 2027 · Event logistics, field coordination and sponsor activation · France, Belgium and Europe.",
    },
    chip: "Recruiter overview",
    essentials: "The essentials · 00:30",
    seeking: ["Seeking an ", "event management internship", ", February → June 2027."],
    intro: "I help event teams prepare logistics, keep participants informed and make partners visible. My experience spans a campus tournament, club sponsorship and event infrastructure in French Guiana.",
    cta: { cv: "Download CV", email: "Email", story: "Follow my story" },
    facts: [
      { k: "Status", v: "Seeking internship" },
      { k: "Window", v: "February → June 2027" },
      { k: "Location", v: "Lille, France" },
      { k: "Languages", v: "FR native · EN C1" },
      { k: "Mobility", v: "France · Belgium · Europe" },
      { k: "Degree", v: "M2 ISA · Lille" },
    ],
    focusKicker: "Contribution",
    focusTitle: "Where I can help",
    focus: [
      { title: "Event operations", body: "Prepare logistics, coordinate on site and adapt when plans change." },
      { title: "Communication & partners", body: "Keep participants informed and make sponsor commitments visible." },
      { title: "Useful production", body: "Deliver photos, content and reusable tools the team can keep using." },
    ],
    projectsKicker: "Experience in practice",
    projectsTitle: "Three projects",
    projectsRight: "Event operations · Partners · Communication",
    contracts: {} as Partial<Record<ContractSlug, ContractOverride>>,
    groundKicker: "On the ground",
    groundTitle: "Beyond the case studies",
    capabilities: [
      "Event logistics",
      "Field coordination",
      "Venue & equipment coordination",
      "Sponsor activation",
      "Bilingual communication",
      "Photography and visual production",
      "Reusable content & digital tools",
    ],
    degree: "M2 International Sport Administration, Université de Lille. Coaching, event infrastructure work and the Navy Reserve shape how I prepare, coordinate and take responsibility.",
    cards: [
      { label: "French Guiana · August 2025", title: "Kourou Beach Festival & Tour de Guyane", body: "Built VIP hospitality structures and installed sponsor arches under event deadlines." },
      { label: "LISSP Calais · 2024–2025", title: "Team travel & tournament logistics", body: "Handled team transport and accommodation alongside U15 and U13 coaching responsibilities." },
    ],
  },
}

export type Copy = typeof en

const fr: Copy = {
  sections: {
    hero: "Accueil",
    contracts: "Projets",
    origin: "Mon parcours",
    operator: "Ma méthode",
    log: "Expérience",
    extraction: "Contact",
  },

  nav: {
    skip: "Aller au contenu",
    home: "Accueil",
    tagline: "// Événementiel sportif",
    briefingShort: "Briefing 30 s",
    briefingLong: "Briefing en 30 secondes",
    sections: "Sections",
    sectionIndex: "Index des sections",
    storyNav: "Navigation",
    openMenu: "Ouvrir le menu",
    closeMenu: "Fermer le menu",
    switchTo: { label: "English version", short: "EN", lang: "en" },
  },

  hero: {
    kicker: "Le regard du joueur",
    portfolio: "Jules Moreau / Portfolio 2026",
    availability: "Disponible pour un stage",
    window: "FÉV. — JUIN 2027",
    role: "Événementiel sportif",
    title: ["Faire vivre", "le sport."],
    specialty: "Opérations événementielles. Communication. Partenariats.",
    intro: "Une expérience concrète sur le terrain, derrière les contenus et aux côtés des partenaires de clubs. Étudiant en M2 International Sport Administration, basé à Lille et mobile partout en Europe.",
    explore: "Voir mes projets",
    talk: "Discutons",
    briefing: "Pressé ? Lisez le briefing en 30 secondes",
    stamp: ["DE JOUEUR", "À ORGANISATEUR."],
    edge: "SUR LE TERRAIN / EN COULISSES",
  },

  work: {
    chapter: "01 / Projets choisis",
    chapterRight: "Trois projets / Expérience concrète",
    title: ["Moins de théorie.", "Plus d’impact."],
    introLabel: "Sur le terrain. Dans le concret.",
    intro: "Faire tourner un tournoi. Donner une voix à un club. Équiper une équipe pour sa prochaine saison. Trois projets, trois façons de faire vivre le sport.",
    languageNote: "Les études de cas détaillées sont en anglais.",
    scene: { featured: "Projet phare", signal: "Contenus en action", field: "Sur le terrain" },
    preview: "Royal Daring / Site partenaires",
    delivery: "Site · Identité · Brochure",
    alts: {
      daringSite: "Site partenaires bilingue du Royal Daring, conçu et livré par Jules",
      daringPacks: "Offres partenaires sur le site livré au Royal Daring",
      signalPhoto: "Jeunes joueurs de l’ASN95 photographiés pour la communication du club et des sponsors",
      signalPoster: "Affiche de match de l’ASN95 créée par Jules",
      field: "Le tournoi universitaire ASI sur le terrain, à Lille",
    },
    featuredProof: ["Site bilingue.", "Un système partenaires complet."],
    openFeatured: "Découvrir le système partenaires",
    open: "Voir l’étude de cas",
    archiveTitle: "Autres projets / Digital, stratégie & photo",
    archiveCount: "04 projets",
    archive: {
      strategy: "Comprendre le business derrière l’esport.",
      "intel-core": "Transformer l’info du jour en outil de veille utile.",
      build: "Créer des sites web pour de vraies organisations.",
      imagery: "Capter les personnes et les moments derrière l’événement.",
    },
    titles: {
      "field-ops": "Tournoi ASI",
      strategy: "Stratégie BLAST",
      build: "Sites clients",
      imagery: "Photographie",
    },
    stories: {
      "field-ops": {
        verb: "Faire tourner.", chapter: "Opérations événementielles",
        text: "Communication et opérations terrain pour un tournoi universitaire de plus de 500 personnes. Faire avancer l’événement quand le plan change.",
        takeaway: "Un événement fonctionne quand les personnes, l’information et le timing fonctionnent ensemble.",
        proof: "500+", proofLabel: "personnes · un tournoi",
      },
      signal: {
        verb: "Faire rayonner.", chapter: "Communication & activation",
        text: "Une saison de contenus, de photos et d’activation sponsors. Construire la présence d’un club autour des personnes qui le font vivre.",
        takeaway: "L’expérience commence avant le jour de match et continue après le coup de sifflet final.",
        proof: "1M+", proofLabel: "vues · une saison",
      },
      daring: {
        verb: "Faire durer.", chapter: "Identité & partenariats",
        text: "Un système complet de prospection sponsors : identité visuelle, site partenaires bilingue, brochure de neuf pages et passation au club. Laisser à l’équipe suivante des outils qu’elle peut continuer à utiliser.",
        takeaway: "Un projet doit laisser à l’équipe suivante une base sur laquelle construire.",
        proof: "FR / NL", proofLabel: "un système partenaires complet",
      },
    },
  },

  story: {
    chapter: "02 / La personne derrière les projets",
    chapterRight: "Compétition → Coaching → Événementiel",
    title: ["Le regard", "du joueur."],
    body: [
      "La compétition dans le jeu vidéo m’a rendu curieux de tout ce qui entoure le match : les gens, la préparation, l’expérience.",
      "Entraîner au volley a amené cette curiosité sur le terrain. Lors d’un tournoi U13 bien organisé, j’ai pu me concentrer sur mon équipe parce que les détails avaient déjà été réglés.",
    ],
    takeawayLabel: "Ce que j’en retiens",
    takeaway: ["Préparer les détails.", "Laisser place au jeu."],
    gamesLink: "Au-delà des projets / Mon histoire de joueur (EN)",
    photoAlt: "Match de volley photographié par Jules Moreau",
    photoTag: "Ma photo / LISSP Calais",
    caption: "Archive photo personnelle · Volley",
    highlights: "Voir mes meilleures actions en compétition",
    video: {
      header: "Racines compétitives",
      play: "Lire les meilleures actions CS2",
      pause: "Mettre en pause les meilleures actions CS2",
      caption: ["Mes actions. Mon regard.", "CS2 / Mes meilleures actions"],
    },
    places: {
      kicker: "Avant les projets / Là où j’ai grandi",
      count: "8 étapes / 4 continents",
      title: ["Quatre continents.", "Une habitude : s’adapter."],
      intro: "J’ai grandi en déménageant avec ma famille. Chaque endroit m’a laissé quelque chose que j’utilise encore.",
      stops: [
        { place: "France", lesson: "Le départ", text: "Né en France. Vingt-quatre jours plus tard, passeport en poche, direction la Guyane." },
        { place: "Guyane", lesson: "La nature", text: "Grandir au contact de la nature, et des singes mains jaunes du balcon." },
        { place: "Corse", lesson: "Le trail", text: "Là où j’ai découvert le trail." },
        { place: "Nouvelle-Calédonie", lesson: "L’océan", text: "Le surf et le va’a, la pirogue à balancier." },
        { place: "Congo · Brazzaville", lesson: "Le recul", text: "Prendre conscience de ma chance." },
        { place: "France", lesson: "Retour", text: "Un premier retour." },
        { place: "Guyane", lesson: "Le jeu", text: "Minecraft, puis Counter-Strike, puis Overwatch." },
        { place: "France", lesson: "Le sport", text: "Les études, le volley, le golf et le jeu en compétition. Puis le management du sport." },
      ],
    },
  },

  approach: {
    chapter: "03 / Ma façon de travailler",
    chapterRight: "Management du sport · Terrain · Curiosité",
    title: ["Un cap.", "Plusieurs compétences."],
    body: "Mon parcours réunit la compétition, le coaching, la discipline militaire et la création. Tout cela nourrit ma façon d’aborder un projet.",
    languages: ["Français / Natif", "Anglais / C1", "FR · BE · Europe"],
    methods: [
      { title: "Préparer le terrain.", text: "Le coaching, le montage d’infrastructures événementielles et la réserve de la Marine m’ont appris à prendre au sérieux la préparation, la coordination et la responsabilité." },
      { title: "Relier les gens.", text: "Une information claire pour une équipe. Des contenus qui font vivre un club. Des partenariats qui donnent à un projet les moyens de grandir." },
      { title: "Construire l’utile.", text: "La photo, les sites web et les outils assistés par l’IA élargissent ce que je peux livrer. J’apprends les outils dont un projet a besoin, puis je les mets au travail." },
    ],
    tools: ["Des outils, quand ils servent", "Canva · Lightroom · Premiere", "Notion · Web · IA"],
  },

  experience: {
    chapter: "04 / Expérience & formation",
    chapterRight: "Lille · Bruxelles · Guyane",
    title: "Sur le terrain.",
    cv: "CV complet / PDF",
    intro: "Une expérience concrète des équipes, du matériel et de la préparation derrière un événement.",
    field: [
      { label: "Infrastructure festival / AOÛT 2025", title: ["Kourou Beach Festival", "& Tour de Guyane"], text: "Montage de l’espace d’hospitalité VIP et installation des arches sponsors avec Bolt Echafaudage, avec des délais serrés." },
      { label: "Logistique d’équipe / 2024 — 2025", title: ["De l’entraînement", "au jour du tournoi"], text: "Organisation du transport et de l’hébergement pour le tournoi de volley d’Ensisheim, en plus de mon rôle d’entraîneur au LISSP Calais." },
      { label: "Esprit d’équipe / DEPUIS 2022", title: ["Préparation.", "Responsabilité."], text: "La réserve de la Marine nationale m’a appris la discipline, l’organisation et la conduite d’équipe sous pression." },
    ],
    education: [
      { label: "2025 — 2027 / Université de Lille", title: "Master · International Sport Administration", text: "Management du sport, gouvernance et esport." },
      { label: "2022 — 2025 / ULCO", title: "Licence · Management du sport", text: "La base académique de mon expérience terrain." },
    ],
    allRoles: "Toute mon expérience",
    roles: "postes",
    deployments: [
      {
        period: "MAI — JUIL. 2026",
        where: "BRUXELLES, BE",
        title: "Stagiaire Communication & Sponsoring",
        org: "Royal Daring Hockey Club ASBL",
        body: "Refonte de la communication et du sponsoring du club avant sa montée en Division Honneur : première charte graphique, système de modèles Canva réutilisables sur 4 formats, offre sponsors en 5 niveaux + Pack Jeunes présentée sur un site partenaires bilingue FR/NL, et passation sous Notion pour assurer la continuité.",
        tag: "STAGE MASTER ISA",
      },
      {
        period: "DÉC. 2025",
        where: "LILLE, FR",
        title: "Responsable communication — Tournoi multisports ASI",
        org: "UFR3S Lille",
        body: "Opérations terrain pour un tournoi universitaire de plus de 500 personnes. Deux incidents critiques (conflit de salle, alerte météo) résolus sans perturber l’événement. Charte graphique, briefing bilingue et affiche réalisés.",
        tag: "TERRAIN",
      },
      {
        period: "AOÛT 2025",
        where: "KOUROU, GUYANE",
        title: "Technicien infrastructure événementielle",
        org: "Bolt Echafaudage",
        body: "Kourou Beach Festival & Tour de Guyane. Montage de l’espace d’hospitalité VIP et installation des arches sponsors avec des délais serrés. Manutention lourde (chariots télescopiques).",
      },
      {
        period: "JUIN — JUIL. 2025",
        where: "GUYANE",
        title: "Vente & support opérationnel",
        org: "Guyane Matériels Groupe",
        body: "Relation client en environnement tropical. Production de photos produits pour les campagnes commerciales.",
      },
      {
        period: "JANV. — JUIN 2025",
        where: "NORTKERQUE, FR",
        title: "Responsable communication",
        org: "AS Nortkerque 95 (ASN95)",
        body: "Création de la présence digitale du club : activation sponsors (+467 % de taux de clic), identité visuelle, opérations jour de match et photo sur toute la saison. Plus d’1M de vues, 44K comptes touchés, +93,8 % d’interactions, +28,2 % d’abonnés.",
        tag: "SIGNAL",
      },
      {
        period: "SEPT. 2024 — JUIN 2025",
        where: "CALAIS, FR",
        title: "Entraîneur de volley — U15 (principal) / U13 (adjoint)",
        org: "LISSP Calais VB",
        body: "Logistique complète de l’équipe, dont le déplacement international (transport, hébergement) pour le tournoi d’Ensisheim.",
      },
      {
        period: "DEPUIS JUIL. 2022",
        where: "FRANCE",
        title: "Réserviste de la Marine nationale — Second maître",
        org: "Marine nationale",
        body: "École de Maistrance. Rigueur militaire, gestion de crise et conduite d’équipe. Missions de réserve opérationnelle axées sur la discipline et l’organisation.",
        tag: "RÉSERVE ACTIVE",
      },
    ],
    personal: "La compétition et la création font toujours partie de mon quotidien.",
    gamesLink: "Au-delà des projets / Mon histoire de joueur (EN)",
  },

  contact: {
    chapter: "05 / Travaillons ensemble",
    chapterRight: "Stage en événementiel / FÉV. — JUIN 2027",
    title: ["Faisons-le", "ensemble."],
    copy: "Besoin de renfort en logistique événementielle, en communication ou en activation partenaires ? Je cherche un stage en événementiel où je peux contribuer sur le terrain.",
    copyStrong: "De février à juin 2027, en France, en Belgique ou ailleurs en Europe.",
    cv: "Télécharger le CV",
    briefing: "Briefing en 30 secondes",
    meta: ["Lille / France", "FR natif · EN C1"],
  },

  footer: {
    line: ["Jules Moreau / De joueur à organisateur.", "Conçu avec curiosité, expérience terrain et outils assistés par l’IA."],
    label: "Pied de page",
    story: "Mon parcours",
    projects: "Projets",
    briefing: "Briefing",
    top: "Haut de page ↑",
    marquee: ["JOUER", "COMPRENDRE", "FAIRE VIVRE"],
  },

  intro: {
    title: "Jules Moreau — Bienvenue dans mon univers",
    description: "Le sport, les projets et le jeu se rassemblent. Vous pouvez passer cette courte introduction.",
    topline: "Sport. Jeu. Création.",
    kicker: "Le regard du joueur",
    note: "Un univers à moi.",
    coordinates: "Toujours en mouvement.",
    phases: { drift: "Ce qui me construit.", gather: "Tout se rassemble.", dive: "Bienvenue." },
    skip: "Passer l’intro",
    labels: {
      daring: "Royal Daring / Identité",
      minecraft: "Minecraft / Ma propre ville",
      volley: "Sur le terrain / Volley",
      asn95: "ASN95 / Jour de match",
      overwatch: "Overwatch / Côté compétition",
      cs: "Counter-Strike / Encore un round",
      playoffs: "Royal Daring / Playoffs",
      website: "Royal Daring / Partenariats",
      skyline: "Minecraft / 250+ heures",
      event: "ASI / Faire vivre le sport",
      osu: "osu! / Rythme & précision",
      places: "Lille / Partout en Europe",
      ball: "Le regard du joueur",
    },
  },

  briefing: {
    meta: {
      title: "Stage en événementiel · février–juin 2027",
      description: "Jules Moreau cherche un stage en événementiel de février à juin 2027. Expérience en opérations terrain, logistique événementielle, communication de club et activation sponsors.",
      ogTitle: "Jules Moreau · Stage en événementiel",
      ogDescription: "Février–juin 2027 · Logistique événementielle, coordination terrain et activation sponsors · France, Belgique et Europe.",
    },
    chip: "Vue recruteur",
    essentials: "L’essentiel · 00:30",
    seeking: ["Je cherche un ", "stage en événementiel", ", de février à juin 2027."],
    intro: "J’aide les équipes événementielles à préparer la logistique, à informer les participants et à rendre les partenaires visibles. Mon expérience va d’un tournoi universitaire au sponsoring de club, en passant par l’infrastructure d’événements en Guyane.",
    cta: { cv: "Télécharger le CV", email: "E-mail", story: "Découvrir mon parcours" },
    facts: [
      { k: "Statut", v: "En recherche de stage" },
      { k: "Période", v: "Février → juin 2027" },
      { k: "Lieu", v: "Lille, France" },
      { k: "Langues", v: "FR natif · EN C1" },
      { k: "Mobilité", v: "France · Belgique · Europe" },
      { k: "Diplôme", v: "M2 ISA · Lille" },
    ],
    focusKicker: "Contribution",
    focusTitle: "Là où je peux aider",
    focus: [
      { title: "Opérations événementielles", body: "Préparer la logistique, coordonner sur place et s’adapter quand le plan change." },
      { title: "Communication & partenaires", body: "Informer les participants et rendre visibles les engagements des sponsors." },
      { title: "Production utile", body: "Livrer des photos, des contenus et des outils réutilisables que l’équipe peut garder." },
    ],
    projectsKicker: "L’expérience en pratique",
    projectsTitle: "Trois projets",
    projectsRight: "Opérations · Partenaires · Communication",
    contracts: {
      "field-ops": {
        title: "Tournoi ASI",
        role: "Responsable communication · opérations terrain",
        summary: "Coordination terrain et communication pour un tournoi universitaire de plus de 500 personnes sur quatre disciplines. Changements de salle et de météo gérés sans perturber l’événement.",
        metricLabel: "personnes · 4 disciplines",
      },
      daring: {
        role: "Communication & sponsoring",
        summary: "La communication éclatée d’un club de hockey amateur centenaire transformée en un système prêt à convaincre des sponsors : charte graphique, site partenaires bilingue, brochure PDF générée par programme, modèles pour les réseaux sociaux et passation sous Notion.",
        metricLabel: "site + 30 visuels",
      },
      signal: {
        role: "Responsable communication",
        summary: "Communication du club par des contenus réguliers, l’activation sponsors et la photo de match. De janvier à juin 2025 : plus d’1M de vues, +93,8 % d’interactions et +467 % de taux de clic sponsors.",
        metricLabel: "taux de clic · 1M de vues",
      },
    },
    groundKicker: "Sur le terrain",
    groundTitle: "Au-delà des études de cas",
    capabilities: [
      "Logistique événementielle",
      "Coordination terrain",
      "Coordination salles & matériel",
      "Activation sponsors",
      "Communication bilingue",
      "Photo et production visuelle",
      "Contenus & outils digitaux réutilisables",
    ],
    degree: "M2 International Sport Administration, Université de Lille. Le coaching, le montage d’infrastructures événementielles et la réserve de la Marine façonnent ma façon de préparer, de coordonner et de prendre mes responsabilités.",
    cards: [
      { label: "Guyane · Août 2025", title: "Kourou Beach Festival & Tour de Guyane", body: "Montage des structures d’hospitalité VIP et installation des arches sponsors dans les délais de l’événement." },
      { label: "LISSP Calais · 2024–2025", title: "Déplacements d’équipe & logistique de tournoi", body: "Gestion du transport et de l’hébergement de l’équipe, en parallèle de l’entraînement des U15 et U13." },
    ],
  },
}

export const COPY: Record<Locale, Copy> = { en, fr }
