/* ------------------------------------------------------------------
   COPY — every visible string of the home page and the briefing, in
   English and French. The French object must mirror the English one.
   ------------------------------------------------------------------ */

import type { ContractSlug } from "@/lib/contracts"
import type { Locale } from "@/lib/i18n"
import { PROJECT_STORIES, type HomeSectionId, type PlaceStop, type ProjectStory, type StorySlug } from "@/lib/journey"
import { DEPLOYMENTS, type Deployment } from "@/lib/profile"

type ContractOverride = { title?: string; role?: string; summary?: string; metricLabel?: string }

const en = {
  sections: {
    hero: "Start",
    contracts: "Selected work",
    origin: "My story",
    operator: "My approach",
    log: "Experience",
    extraction: "Contact",
  } as Record<HomeSectionId, string>,

  nav: {
    skip: "Skip to content",
    home: "Home",
    tagline: "// Digital transformation & AI",
    briefingShort: "30-sec briefing",
    briefingLong: "30-second briefing",
    sections: "Sections",
    sectionIndex: "Section index",
    storyNav: "Story navigation",
    openMenu: "Open navigation",
    closeMenu: "Close navigation",
    switchTo: { label: "Version française", short: "FR", lang: "fr" },
  },

  hero: {
    kicker: "A player's perspective",
    portfolio: "Jules Moreau / Portfolio 2026",
    availability: "Open to an internship",
    window: "FEB — JUN 2027",
    role: "Digital transformation & AI",
    title: ["Upgrade", "the game."],
    specialty: "AI, automation and better processes for sport organisations.",
    intro: "Club communication, partnerships and events showed me where small sport organisations lose time. Now I build the AI tools and automations that give it back, and help teams actually use them. M2 International Sport Administration student in Lille, writing my thesis on generative AI in sports associations.",
    explore: "Explore my work",
    talk: "Let's talk",
    briefing: "Short on time? Read the 30-second briefing",
    stamp: ["FROM THE FIELD", "TO THE TOOLS."],
    edge: "WITH THE TEAM / INSIDE THE TOOLS",
  },

  work: {
    chapter: "01 / Selected work",
    chapterRight: "Four projects / AI, tools & the field",
    title: ["Find the friction.", "Build the tool."],
    introLabel: "Real teams. Real tools.",
    intro: "An AI research engine running 24/7. A sponsor system built so a club can run it without me. Then the tournament and the season where I learned how sport organisations really work.",
    languageNote: "",
    scene: { featured: "Built to last", signal: "Built from scratch", field: "On the ground" },
    preview: "Royal Daring / Partner website",
    delivery: "Website · Templates · Notion",
    alts: {
      daringSite: "Bilingual Royal Daring partner website designed and delivered by Jules",
      daringPacks: "Partner packages on the delivered Royal Daring website",
      signalPhoto: "ASN95 youth players photographed for club and sponsor communication",
      signalPoster: "ASN95 match poster created by Jules",
      field: "ASI university tournament on the ground in Lille",
    },
    featuredProof: ["ready-to-use post templates.", "A handover any volunteer can pick up."],
    openFeatured: "Inside the system",
    open: "Explore the case study",
    lab: {
      label: "Featured project / Live R&D",
      right: "Running now",
      code: "01 / THS",
      status: "Live · running 24/7",
      identity: "Thesis Engine",
      chapter: "AI research pipeline · M2 thesis",
      offer: ["Available soon", "Adaptable to any sector"],
      verb: ["Make it", "think."],
      text: "My thesis asks what generative AI can do for sports associations with limited resources. My research runs on exactly that: a local, fine-tuned model that scans three research databases three times a day, keeps what matters and files it into my Obsidian vault.",
      proof: "90",
      proofLabel: "sources a day · ~5% kept",
      cost: "≈ €0",
      costLabel: "a month · runs locally, 24/7",
      open: "Explore the engine",
      chainLabel: "Scholar · OpenAlex · Cairn → Qwen3 4B → Obsidian",
    },
    archiveTitle: "More projects / Digital, strategy & photography",
    archiveCount: "03 projects",
    archive: {
      strategy: "Understanding the business behind esports.",
      build: "Websites for real organisations, built with AI.",
      imagery: "Capturing the people and moments behind the event.",
    } as Partial<Record<ContractSlug, string>>,
    titles: {} as Partial<Record<ContractSlug, string>>,
    stories: PROJECT_STORIES as Record<StorySlug, ProjectStory>,
  },

  story: {
    chapter: "02 / The person behind the work",
    chapterRight: "Competition → Field → Tools → AI",
    title: ["From the field", "to the tools."],
    body: [
      "Competitive gaming made me curious about everything around the match. Coaching volleyball showed me why it matters: at a well-organised U13 tournament, I could focus on my team because the details had already been taken care of.",
      "Then came the field: club communication, partnerships, a 500-person tournament. Each time, the same pattern. Small sport organisations run on volunteers, and much of their time goes into tasks a good tool could take over. So I started building those tools.",
    ],
    takeawayLabel: "What stayed with me",
    takeaway: ["The best tool", "is the one the team keeps using."],
    gamesLink: "Beyond the work / My gaming story",
    photoAlt: "Volleyball match photographed by Jules Moreau",
    photoTag: "My photography / LISSP Calais",
    caption: "Personal photography archive · Volleyball",
    highlights: "Watch my competitive gaming highlights",
    video: {
      header: "Competitive roots",
      play: "Play CS2 highlights",
      pause: "Pause CS2 highlights",
      caption: ["My plays. My perspective.", "CS2 / My highlights"],
    },
    path: {
      kicker: "The turning point / From the field to the tools",
      count: "4 steps",
      title: ["Same curiosity.", "New tools."],
      intro: "The direction changed. The habit didn't: look at how things really work, then make them work better.",
      steps: [
        { stage: "Competition", when: "Gaming · volleyball", lesson: "Understand the game", text: "Overwatch and Counter-Strike, then coaching U15 and U13 volleyball. Curious about everything around the match." },
        { stage: "The field", when: "2024 — 2025", lesson: "See where time goes", text: "Club communication at ASN95, a 500-person tournament, festival infrastructure in French Guiana." },
        { stage: "The tools", when: "2026", lesson: "Build what stays", text: "At Royal Daring: a Notion workspace, 11 templates and a partner website the club can run without me." },
        { stage: "AI", when: "Since Oct 2026", lesson: "Make it think", text: "The Thesis Engine runs my research 24/7. My thesis asks what generative AI can do for sports associations." },
      ],
    },
    places: {
      kicker: "Before the work / Where I grew up",
      count: "8 moves / 4 continents",
      title: ["Four continents.", "One habit: adapt."],
      intro: "I grew up moving with my family. Each place left me something I still use.",
      stops: [
        { place: "France", at: "france", lesson: "The start", text: "Born here. Twenty-four days later, passport in hand, off to French Guiana." },
        { place: "French Guiana", at: "guiana", lesson: "Nature", text: "Growing up close to nature, and to the golden-handed tamarins on our balcony." },
        { place: "Corsica", at: "corsica", lesson: "Trail running", text: "Where trail running started for me." },
        { place: "New Caledonia", at: "caledonia", lesson: "The ocean", text: "Surfing and va'a, the outrigger canoe." },
        { place: "Congo · Brazzaville", at: "congo", lesson: "Perspective", text: "Realising how lucky I was." },
        { place: "France", at: "france", lesson: "Back home", text: "A first return." },
        { place: "French Guiana", at: "guiana", lesson: "Games", text: "Minecraft, then Counter-Strike, then Overwatch." },
        { place: "France", at: "france", lesson: "Sport", text: "Studies, volleyball, golf and competitive gaming. Then sport management." },
      ] as PlaceStop[],
      mapLabel: "World map of the eight moves: France, French Guiana, Corsica, New Caledonia, Congo, then France, French Guiana and France again.",
      compass: { n: "N", s: "S", e: "E", w: "W" },
      controls: { prev: "Previous move", next: "Next move", replay: "Replay the journey" },
    },
  },

  approach: {
    chapter: "03 / How I work",
    chapterRight: "Observe · Build · Hand over",
    title: ["People first.", "Then the tool."],
    body: "In a small sport organisation, digital transformation is not about the newest tool. It is about the volunteer on a Sunday evening, the coach with ten minutes to spare, the intern who arrives next season. I build for them.",
    languages: ["French / Native", "English / C1", "FR · BE · Europe"],
    methods: [
      { title: "Map how it really works.", text: "Before automating anything, I look at how the team actually works: who does what, where information gets stuck, which tasks come back every week. Coaching, event operations and the Navy Reserve taught me to prepare before acting." },
      { title: "Build the smallest useful tool.", text: "A Notion workspace, templates, an automation, a local AI model: I pick the simplest thing that removes the friction, and build it with AI-assisted tools like Claude Code." },
      { title: "Hand it over.", text: "A tool only counts if the team keeps using it after I leave. Clear documentation, a reading guide for whoever comes next, exports any AI assistant can read: that is how the Royal Daring handover was built." },
    ],
    tools: ["Tools, when they help", "Notion · Obsidian · Canva", "Claude Code · Codex · Ollama · local LLMs"],
  },

  experience: {
    chapter: "04 / Experience & education",
    chapterRight: "Lille · Brussels · French Guiana",
    title: "Field-tested.",
    cv: "Full CV / PDF",
    intro: "Before building tools for sport organisations, I worked inside them: on site, with volunteers, against the clock.",
    field: [
      { label: "Festival infrastructure / AUG 2025", title: ["Kourou Beach Festival", "& Tour de Guyane"], text: "Built the VIP hospitality complex and deployed sponsor arches with Bolt Echafaudage, under strict timing constraints." },
      { label: "Team logistics / 2024 — 2025", title: ["From training", "to tournament day"], text: "Organised transport and accommodation for the Ensisheim volleyball tournament alongside my coaching responsibilities at LISSP Calais." },
      { label: "Teamwork / SINCE 2022", title: ["Preparation.", "Responsibility."], text: "French Navy Reserve service taught me discipline, organisation and team leadership under pressure." },
    ],
    education: [
      { label: "2025 — 2027 / Université de Lille", title: "Master’s · International Sport Administration", text: "Sport management and governance. Thesis on generative AI and no-code tools in sports associations." },
      { label: "2022 — 2025 / ULCO", title: "Bachelor’s · Sport Management", text: "The academic foundation behind my field experience." },
    ],
    allRoles: "Explore all experience",
    roles: "roles",
    deployments: DEPLOYMENTS as Deployment[],
    personal: "Competition and creativity are still part of my everyday life.",
    gamesLink: "Beyond the projects / My gaming story",
  },

  contact: {
    chapter: "05 / Let's work together",
    chapterRight: "Digital transformation & AI internship / FEB — JUN 2027",
    title: ["Let's make", "it happen."],
    copy: "Repetitive tasks, scattered information, tools nobody really uses? I am looking for a digital transformation & AI internship in a sport organisation, to map your processes, automate what can be automated and help your team adopt the tools.",
    copyStrong: "February to June 2027, in France, Belgium or elsewhere in Europe.",
    cv: "Download CV",
    briefing: "30-second briefing",
    meta: ["Lille / France", "FR native · EN C1"],
  },

  footer: {
    line: ["Jules Moreau / From the field to the tools.", "Built with curiosity, field experience and AI-assisted tools."],
    label: "Footer",
    story: "My story",
    projects: "Projects",
    briefing: "Briefing",
    top: "Back to top ↑",
    marquee: ["PLAY", "UNDERSTAND", "BUILD"],
  },

  intro: {
    title: "Jules Moreau — Welcome to my world",
    description: "Sport, projects and games coming together. You can skip this short introduction.",
    topline: "Sport. Play. Create.",
    kicker: "A player's perspective",
    note: "A world of my own.",
    coordinates: "Always in motion.",
    phases: { drift: "A few things that make me.", gather: "All coming together.", dive: "Welcome in." },
    skip: "Skip intro",
    labels: {} as Record<string, string>,
  },

  briefing: {
    meta: {
      title: "Digital transformation & AI internship · February–June 2027",
      description: "Jules Moreau is seeking a digital transformation & AI internship in a sport organisation, February to June 2027: process mapping, automation, AI tools and team adoption, backed by field experience in clubs and events.",
      ogTitle: "Jules Moreau · Digital transformation & AI internship",
      ogDescription: "February–June 2027 · AI tools, automation and team adoption for sport organisations · France, Belgium and Europe.",
    },
    chip: "Recruiter overview",
    essentials: "The essentials · 00:30",
    seeking: ["Seeking a ", "digital transformation & AI internship", ", February → June 2027."],
    intro: "I help sport organisations see how they really work, automate what comes back every week and adopt AI tools their teams keep using. Behind it: club communication, partnerships and events, and an M2 thesis on generative AI in sports associations.",
    cta: { cv: "Download CV", email: "Email", story: "Follow my story" },
    facts: [
      { k: "Status", v: "Seeking internship" },
      { k: "Window", v: "February → June 2027" },
      { k: "Location", v: "Lille, France" },
      { k: "Languages", v: "FR native · EN C1" },
      { k: "Mobility", v: "France · Belgium · Europe" },
      { k: "Degree", v: "M2 ISA · Lille" },
    ],
    focusKicker: "Contribution",
    focusTitle: "Where I can help",
    focus: [
      { title: "Map the processes", body: "See how the team really works, where information gets stuck and which tasks come back every week." },
      { title: "Automate & equip", body: "Build the simplest useful tool: Notion workspaces, templates, automations, AI assistants." },
      { title: "Drive adoption", body: "Document, hand over and help staff and volunteers keep using the tools after launch." },
    ],
    projectsKicker: "Experience in practice",
    projectsTitle: "Three projects",
    projectsRight: "AI · Tools & handover · Digital",
    contracts: {
      "thesis-engine": { metricLabel: "sources a day" },
      daring: {
        summary: "A sponsor system built to outlive the internship: brand guidelines, a bilingual partner website, Canva templates and a Notion handover workspace for volunteers, exported in Markdown for any AI assistant.",
      },
      signal: {
        summary: "A club's digital presence built from scratch, with no content calendar or guidelines: three recurring formats, a weekly sponsor prediction game (+467% sponsor click-through rate) and a first app concept. 1M+ views in one season.",
      },
    } as Partial<Record<ContractSlug, ContractOverride>>,
    groundKicker: "Toolkit",
    groundTitle: "Beyond the case studies",
    capabilities: [
      "Process mapping",
      "Workflow automation",
      "AI assistants & local LLMs",
      "Notion workspaces & handovers",
      "AI-assisted builds (Claude Code, Codex)",
      "Bilingual documentation FR/EN",
      "Club & event field experience",
    ],
    degree: "M2 International Sport Administration, Université de Lille. Thesis: how generative AI and no-code tools can make sports associations with limited resources more efficient. Coaching, event operations and the Navy Reserve shape how I prepare, coordinate and take responsibility.",
    cards: [
      { label: "Royal Daring · May–July 2026", title: "A handover built to last", body: "A Notion workspace for volunteers and the next intern: starting diagnostic, editorial charter, 11 post templates and a live task tracker, exported in Markdown for any AI assistant." },
      { label: "ASI Tournament · December 2025", title: "500+ people, one briefing", body: "A bilingual FR/EN participant briefing, and a new venue secured in 45 minutes when the main gym was taken two hours before the start." },
    ],
  },
}

export type Copy = typeof en

const fr: Copy = {
  sections: {
    hero: "Accueil",
    contracts: "Projets",
    origin: "Mon parcours",
    operator: "Ma méthode",
    log: "Expérience",
    extraction: "Contact",
  },

  nav: {
    skip: "Aller au contenu",
    home: "Accueil",
    tagline: "// Transformation digitale & IA",
    briefingShort: "Briefing 30 s",
    briefingLong: "Briefing en 30 secondes",
    sections: "Sections",
    sectionIndex: "Index des sections",
    storyNav: "Navigation",
    openMenu: "Ouvrir le menu",
    closeMenu: "Fermer le menu",
    switchTo: { label: "English version", short: "EN", lang: "en" },
  },

  hero: {
    kicker: "Le regard du joueur",
    portfolio: "Jules Moreau / Portfolio 2026",
    availability: "Disponible pour un stage",
    window: "FÉV. — JUIN 2027",
    role: "Transformation digitale & IA",
    title: ["Outiller", "le sport."],
    specialty: "IA, automatisation et process pour les structures sportives.",
    intro: "La communication de club, les partenariats et l’événementiel m’ont montré où les petites structures sportives perdent du temps. Aujourd’hui, je construis les outils IA et les automatisations qui leur en font gagner, et j’aide les équipes à s’en servir. En M2 International Sport Administration à Lille, mémoire sur l’IA générative dans les associations sportives.",
    explore: "Voir mes projets",
    talk: "Discutons",
    briefing: "Pressé ? Lisez le briefing en 30 secondes",
    stamp: ["DU TERRAIN", "AUX OUTILS."],
    edge: "AVEC L’ÉQUIPE / DANS LES OUTILS",
  },

  work: {
    chapter: "01 / Projets choisis",
    chapterRight: "Quatre projets / IA, outils & terrain",
    title: ["Trouver le frein.", "Bâtir l’outil."],
    introLabel: "De vraies équipes. De vrais outils.",
    intro: "Un moteur de recherche IA qui tourne 24h/24. Un système sponsors pensé pour qu’un club le fasse vivre sans moi. Puis le tournoi et la saison où j’ai appris comment fonctionnent vraiment les structures sportives.",
    languageNote: "Les études de cas détaillées sont en anglais.",
    scene: { featured: "Conçu pour durer", signal: "Parti de zéro", field: "Sur le terrain" },
    preview: "Royal Daring / Site partenaires",
    delivery: "Site · Modèles · Notion",
    alts: {
      daringSite: "Site partenaires bilingue du Royal Daring, conçu et livré par Jules",
      daringPacks: "Offres partenaires sur le site livré au Royal Daring",
      signalPhoto: "Jeunes joueurs de l’ASN95 photographiés pour la communication du club et des sponsors",
      signalPoster: "Affiche de match de l’ASN95 créée par Jules",
      field: "Le tournoi universitaire ASI sur le terrain, à Lille",
    },
    featuredProof: ["modèles de posts prêts à l’emploi.", "Une passation que tout bénévole peut reprendre."],
    openFeatured: "Découvrir le système",
    open: "Voir l’étude de cas",
    lab: {
      label: "Projet phare / R&D en direct",
      right: "En ce moment",
      code: "01 / THS",
      status: "En direct · 24h/24",
      identity: "Thesis Engine",
      chapter: "Pipeline de recherche IA · mémoire M2",
      offer: ["Bientôt disponible", "Adaptable à tout secteur"],
      verb: ["Faire", "réfléchir."],
      text: "Mon mémoire étudie ce que l’IA générative peut apporter aux associations sportives aux moyens limités. Ma recherche tourne exactement là-dessus : un modèle local fine-tuné qui scanne trois bases scientifiques trois fois par jour, garde l’essentiel et le range dans mon vault Obsidian.",
      proof: "90",
      proofLabel: "sources par jour · ~5 % gardées",
      cost: "≈ 0 €",
      costLabel: "par mois · tourne en local, 24h/24",
      open: "Explorer le moteur",
      chainLabel: "Scholar · OpenAlex · Cairn → Qwen3 4B → Obsidian",
    },
    archiveTitle: "Autres projets / Digital, stratégie & photo",
    archiveCount: "03 projets",
    archive: {
      strategy: "Comprendre le business derrière l’esport.",
      build: "Des sites pour de vraies organisations, construits avec l’IA.",
      imagery: "Capter les personnes et les moments derrière l’événement.",
    },
    titles: {
      "field-ops": "Tournoi ASI",
      strategy: "Stratégie BLAST",
      build: "Sites clients",
      imagery: "Photographie",
    },
    stories: {
      "field-ops": {
        verb: "Faire tourner.", chapter: "Opérations événementielles",
        text: "Communication et opérations terrain pour un tournoi universitaire de plus de 500 personnes : un briefing bilingue pour chaque participant, et une nouvelle salle trouvée en 45 minutes quand le plan a changé.",
        takeaway: "Un événement fonctionne quand les personnes, l’information et le timing fonctionnent ensemble.",
        proof: "500+", proofLabel: "personnes · un tournoi",
      },
      signal: {
        verb: "Faire rayonner.", chapter: "Digital & activation sponsors",
        text: "La présence digitale d’un club construite de zéro, sans calendrier ni charte au départ : trois formats récurrents, un jeu de pronostics sponsorisé chaque semaine et un premier concept d’appli.",
        takeaway: "L’expérience commence avant le jour de match et continue après le coup de sifflet final.",
        proof: "1M+", proofLabel: "vues · une saison",
      },
      daring: {
        verb: "Faire durer.", chapter: "Outils & passation",
        text: "Un système sponsors conçu pour survivre à mon stage : charte graphique, site partenaires bilingue, modèles Canva et un espace Notion pour que les bénévoles continuent de produire seuls, exporté en Markdown pour n’importe quel assistant IA.",
        takeaway: "Un projet doit laisser à l’équipe suivante une base sur laquelle construire.",
        proof: "11", proofLabel: "modèles de posts prêts à l’emploi",
      },
    },
  },

  story: {
    chapter: "02 / La personne derrière les projets",
    chapterRight: "Compétition → Terrain → Outils → IA",
    title: ["Du terrain", "aux outils."],
    body: [
      "La compétition dans le jeu vidéo m’a rendu curieux de tout ce qui entoure le match. Entraîner au volley m’a montré pourquoi c’est important : lors d’un tournoi U13 bien organisé, j’ai pu me concentrer sur mon équipe parce que les détails avaient déjà été réglés.",
      "Puis le terrain : la communication de club, les partenariats, un tournoi de 500 personnes. À chaque fois, le même constat : les petites structures sportives tiennent grâce aux bénévoles, et une bonne partie de leur temps part dans des tâches qu’un bon outil pourrait prendre en charge. Alors j’ai commencé à construire ces outils.",
    ],
    takeawayLabel: "Ce que j’en retiens",
    takeaway: ["Le meilleur outil,", "c’est celui que l’équipe continue d’utiliser."],
    gamesLink: "Au-delà des projets / Mon histoire de joueur (EN)",
    photoAlt: "Match de volley photographié par Jules Moreau",
    photoTag: "Ma photo / LISSP Calais",
    caption: "Archive photo personnelle · Volley",
    highlights: "Voir mes meilleures actions en compétition",
    video: {
      header: "Racines compétitives",
      play: "Lire les meilleures actions CS2",
      pause: "Mettre en pause les meilleures actions CS2",
      caption: ["Mes actions. Mon regard.", "CS2 / Mes meilleures actions"],
    },
    path: {
      kicker: "Le virage / Du terrain aux outils",
      count: "4 étapes",
      title: ["Même curiosité.", "Nouveaux outils."],
      intro: "Le cap a changé. L’habitude, non : regarder comment les choses fonctionnent vraiment, puis les faire mieux fonctionner.",
      steps: [
        { stage: "Compétition", when: "Jeu vidéo · volley", lesson: "Comprendre le jeu", text: "Overwatch et Counter-Strike, puis entraîneur de volley en U15 et U13. Curieux de tout ce qui entoure le match." },
        { stage: "Le terrain", when: "2024 — 2025", lesson: "Voir où part le temps", text: "La communication de l’ASN95, un tournoi de 500 personnes, l’infrastructure d’un festival en Guyane." },
        { stage: "Les outils", when: "2026", lesson: "Construire ce qui reste", text: "Au Royal Daring : un espace Notion, 11 modèles et un site partenaires que le club peut faire vivre sans moi." },
        { stage: "L’IA", when: "Depuis oct. 2026", lesson: "Faire réfléchir", text: "Le Thesis Engine fait tourner ma recherche 24h/24. Mon mémoire étudie ce que l’IA générative peut apporter aux associations sportives." },
      ],
    },
    places: {
      kicker: "Avant les projets / Là où j’ai grandi",
      count: "8 étapes / 4 continents",
      title: ["Quatre continents.", "Une habitude : s’adapter."],
      intro: "J’ai grandi en déménageant avec ma famille. Chaque endroit m’a laissé quelque chose que j’utilise encore.",
      stops: [
        { place: "France", at: "france", lesson: "Le départ", text: "Né en France. Vingt-quatre jours plus tard, passeport en poche, direction la Guyane." },
        { place: "Guyane", at: "guiana", lesson: "La nature", text: "Grandir au contact de la nature, et des singes mains jaunes du balcon." },
        { place: "Corse", at: "corsica", lesson: "Le trail", text: "Là où j’ai découvert le trail." },
        { place: "Nouvelle-Calédonie", at: "caledonia", lesson: "L’océan", text: "Le surf et le va’a, la pirogue à balancier." },
        { place: "Congo · Brazzaville", at: "congo", lesson: "Le recul", text: "Prendre conscience de ma chance." },
        { place: "France", at: "france", lesson: "Retour", text: "Un premier retour." },
        { place: "Guyane", at: "guiana", lesson: "Le jeu", text: "Minecraft, puis Counter-Strike, puis Overwatch." },
        { place: "France", at: "france", lesson: "Le sport", text: "Les études, le volley, le golf et le jeu en compétition. Puis le management du sport." },
      ],
      mapLabel: "Carte du monde des huit étapes : France, Guyane, Corse, Nouvelle-Calédonie, Congo, puis France, Guyane et de nouveau France.",
      compass: { n: "N", s: "S", e: "E", w: "O" },
      controls: { prev: "Étape précédente", next: "Étape suivante", replay: "Rejouer le trajet" },
    },
  },

  approach: {
    chapter: "03 / Ma façon de travailler",
    chapterRight: "Observer · Construire · Transmettre",
    title: ["Les gens d’abord.", "L’outil ensuite."],
    body: "Dans une petite structure sportive, la transformation digitale ne se joue pas sur l’outil le plus récent. Elle se joue sur le bénévole le dimanche soir, l’entraîneur qui a dix minutes devant lui, le stagiaire qui arrivera la saison prochaine. C’est pour eux que je construis.",
    languages: ["Français / Natif", "Anglais / C1", "FR · BE · Europe"],
    methods: [
      { title: "Comprendre comment ça marche vraiment.", text: "Avant d’automatiser quoi que ce soit, je regarde comment l’équipe travaille vraiment : qui fait quoi, où l’information se perd, quelles tâches reviennent chaque semaine. Le coaching, l’événementiel et la réserve de la Marine m’ont appris à préparer avant d’agir." },
      { title: "Construire le plus petit outil utile.", text: "Un espace Notion, des templates, une automatisation, une IA locale : je choisis la solution la plus simple qui lève le frein, et je la construis avec des outils assistés par l’IA comme Claude Code." },
      { title: "Transmettre.", text: "Un outil ne compte que si l’équipe continue de s’en servir après mon départ. Une documentation claire, un guide de lecture pour la personne suivante, des exports lisibles par n’importe quel assistant IA : c’est comme ça qu’a été pensée la passation au Royal Daring." },
    ],
    tools: ["Des outils, quand ils servent", "Notion · Obsidian · Canva", "Claude Code · Codex · Ollama · LLM locaux"],
  },

  experience: {
    chapter: "04 / Expérience & formation",
    chapterRight: "Lille · Bruxelles · Guyane",
    title: "Testé sur le terrain.",
    cv: "CV complet / PDF",
    intro: "Avant de construire des outils pour les structures sportives, j’ai travaillé à l’intérieur : sur site, avec des bénévoles, contre la montre.",
    field: [
      { label: "Infrastructure festival / AOÛT 2025", title: ["Kourou Beach Festival", "& Tour de Guyane"], text: "Montage de l’espace d’hospitalité VIP et installation des arches sponsors avec Bolt Echafaudage, avec des délais serrés." },
      { label: "Logistique d’équipe / 2024 — 2025", title: ["De l’entraînement", "au jour du tournoi"], text: "Organisation du transport et de l’hébergement pour le tournoi de volley d’Ensisheim, en plus de mon rôle d’entraîneur au LISSP Calais." },
      { label: "Esprit d’équipe / DEPUIS 2022", title: ["Préparation.", "Responsabilité."], text: "La réserve de la Marine nationale m’a appris la discipline, l’organisation et la conduite d’équipe sous pression." },
    ],
    education: [
      { label: "2025 — 2027 / Université de Lille", title: "Master · International Sport Administration", text: "Management et gouvernance du sport. Mémoire sur l’IA générative et le no-code dans les associations sportives." },
      { label: "2022 — 2025 / ULCO", title: "Licence · Management du sport", text: "La base académique de mon expérience terrain." },
    ],
    allRoles: "Toute mon expérience",
    roles: "postes",
    deployments: [
      {
        period: "MAI — JUIL. 2026",
        where: "BRUXELLES, BE",
        title: "Stagiaire Communication & Sponsoring",
        org: "Royal Daring Hockey Club ASBL",
        body: "Refonte de la communication et du sponsoring du club avant sa montée en Division Honneur : première charte graphique, système de modèles Canva réutilisables sur 4 formats, offre sponsors en 5 niveaux + Pack Jeunes présentée sur un site partenaires bilingue FR/NL, et passation sous Notion pour assurer la continuité.",
        tag: "STAGE MASTER ISA",
      },
      {
        period: "DÉC. 2025",
        where: "LILLE, FR",
        title: "Responsable communication — Tournoi multisports ASI",
        org: "UFR3S Lille",
        body: "Opérations terrain pour un tournoi universitaire de plus de 500 personnes. Deux incidents critiques (conflit de salle, alerte météo) résolus sans perturber l’événement. Charte graphique, briefing bilingue et affiche réalisés.",
        tag: "TERRAIN",
      },
      {
        period: "AOÛT 2025",
        where: "KOUROU, GUYANE",
        title: "Technicien infrastructure événementielle",
        org: "Bolt Echafaudage",
        body: "Kourou Beach Festival & Tour de Guyane. Montage de l’espace d’hospitalité VIP et installation des arches sponsors avec des délais serrés. Manutention lourde (chariots télescopiques).",
      },
      {
        period: "JUIN — JUIL. 2025",
        where: "GUYANE",
        title: "Vente & support opérationnel",
        org: "Guyane Matériels Groupe",
        body: "Relation client en environnement tropical. Production de photos produits pour les campagnes commerciales.",
      },
      {
        period: "JANV. — JUIN 2025",
        where: "NORTKERQUE, FR",
        title: "Responsable communication",
        org: "AS Nortkerque 95 (ASN95)",
        body: "Création de la présence digitale du club : activation sponsors (+467 % de taux de clic), identité visuelle, opérations jour de match et photo sur toute la saison. Plus d’1M de vues, 44K comptes touchés, +93,8 % d’interactions, +28,2 % d’abonnés.",
        tag: "SIGNAL",
      },
      {
        period: "SEPT. 2024 — JUIN 2025",
        where: "CALAIS, FR",
        title: "Entraîneur de volley — U15 (principal) / U13 (adjoint)",
        org: "LISSP Calais VB",
        body: "Logistique complète de l’équipe, dont le déplacement international (transport, hébergement) pour le tournoi d’Ensisheim.",
      },
      {
        period: "DEPUIS JUIL. 2022",
        where: "FRANCE",
        title: "Réserviste de la Marine nationale — Second maître",
        org: "Marine nationale",
        body: "École de Maistrance. Rigueur militaire, gestion de crise et conduite d’équipe. Missions de réserve opérationnelle axées sur la discipline et l’organisation.",
        tag: "RÉSERVE ACTIVE",
      },
    ],
    personal: "La compétition et la création font toujours partie de mon quotidien.",
    gamesLink: "Au-delà des projets / Mon histoire de joueur (EN)",
  },

  contact: {
    chapter: "05 / Travaillons ensemble",
    chapterRight: "Stage transformation digitale & IA / FÉV. — JUIN 2027",
    title: ["Faisons-le", "ensemble."],
    copy: "Des tâches répétitives, une information éparpillée, des outils que personne n’utilise vraiment ? Je cherche un stage en transformation digitale & IA dans une structure sportive, pour cartographier vos process, automatiser ce qui peut l’être et accompagner votre équipe dans l’adoption des outils.",
    copyStrong: "De février à juin 2027, en France, en Belgique ou ailleurs en Europe.",
    cv: "Télécharger le CV",
    briefing: "Briefing en 30 secondes",
    meta: ["Lille / France", "FR natif · EN C1"],
  },

  footer: {
    line: ["Jules Moreau / Du terrain aux outils.", "Conçu avec curiosité, expérience terrain et outils assistés par l’IA."],
    label: "Pied de page",
    story: "Mon parcours",
    projects: "Projets",
    briefing: "Briefing",
    top: "Haut de page ↑",
    marquee: ["JOUER", "COMPRENDRE", "CONSTRUIRE"],
  },

  intro: {
    title: "Jules Moreau — Bienvenue dans mon univers",
    description: "Le sport, les projets et le jeu se rassemblent. Vous pouvez passer cette courte introduction.",
    topline: "Sport. Jeu. Création.",
    kicker: "Le regard du joueur",
    note: "Un univers à moi.",
    coordinates: "Toujours en mouvement.",
    phases: { drift: "Ce qui me construit.", gather: "Tout se rassemble.", dive: "Bienvenue." },
    skip: "Passer l’intro",
    labels: {
      daring: "Royal Daring / Identité",
      minecraft: "Minecraft / Ma propre ville",
      volley: "Sur le terrain / Volley",
      asn95: "ASN95 / Jour de match",
      overwatch: "Overwatch / Côté compétition",
      cs: "Counter-Strike / Encore un round",
      playoffs: "Royal Daring / Playoffs",
      website: "Royal Daring / Partenariats",
      skyline: "Minecraft / 250+ heures",
      event: "ASI / Faire vivre le sport",
      osu: "osu! / Rythme & précision",
      places: "Lille / Partout en Europe",
      ball: "Le regard du joueur",
    },
  },

  briefing: {
    meta: {
      title: "Stage transformation digitale & IA · février–juin 2027",
      description: "Jules Moreau cherche un stage en transformation digitale & IA dans une structure sportive, de février à juin 2027 : cartographie des process, automatisation, outils IA et adoption par les équipes, appuyés sur une expérience terrain en clubs et en événementiel.",
      ogTitle: "Jules Moreau · Stage transformation digitale & IA",
      ogDescription: "Février–juin 2027 · Outils IA, automatisation et adoption par les équipes pour les structures sportives · France, Belgique et Europe.",
    },
    chip: "Vue recruteur",
    essentials: "L’essentiel · 00:30",
    seeking: ["Je cherche un ", "stage en transformation digitale & IA", ", de février à juin 2027."],
    intro: "J’aide les structures sportives à voir comment elles fonctionnent vraiment, à automatiser ce qui revient chaque semaine et à adopter des outils IA que leurs équipes continuent d’utiliser. Derrière : la communication de club, les partenariats, l’événementiel, et un mémoire de M2 sur l’IA générative dans les associations sportives.",
    cta: { cv: "Télécharger le CV", email: "E-mail", story: "Découvrir mon parcours" },
    facts: [
      { k: "Statut", v: "En recherche de stage" },
      { k: "Période", v: "Février → juin 2027" },
      { k: "Lieu", v: "Lille, France" },
      { k: "Langues", v: "FR natif · EN C1" },
      { k: "Mobilité", v: "France · Belgique · Europe" },
      { k: "Diplôme", v: "M2 ISA · Lille" },
    ],
    focusKicker: "Contribution",
    focusTitle: "Là où je peux aider",
    focus: [
      { title: "Cartographier les process", body: "Voir comment l’équipe travaille vraiment, où l’information se perd et quelles tâches reviennent chaque semaine." },
      { title: "Automatiser & outiller", body: "Construire l’outil utile le plus simple : espaces Notion, templates, automatisations, assistants IA." },
      { title: "Faire adopter", body: "Documenter, transmettre et aider salariés et bénévoles à continuer d’utiliser les outils après le lancement." },
    ],
    projectsKicker: "L’expérience en pratique",
    projectsTitle: "Trois projets",
    projectsRight: "IA · Outils & passation · Digital",
    contracts: {
      "thesis-engine": {
        role: "Conception & exploitation · build assisté par l’IA",
        summary: "Un moteur de recherche local pour mon mémoire de M2 : trois scans par jour sur Google Scholar, OpenAlex et Cairn, un tri par un Qwen3 4B fine-tuné, Claude Sonnet quand l’analyse devient complexe, et tout arrive directement dans mon vault Obsidian.",
        metricLabel: "sources par jour",
      },
      daring: {
        role: "Communication & sponsoring",
        summary: "Un système sponsors conçu pour survivre au stage : charte graphique, site partenaires bilingue, modèles Canva et un espace Notion de passation pour les bénévoles, exporté en Markdown pour n’importe quel assistant IA.",
        metricLabel: "site + 30 visuels",
      },
      signal: {
        role: "Responsable communication",
        summary: "La présence digitale d’un club construite de zéro, sans calendrier ni charte : trois formats récurrents, un jeu de pronostics sponsorisé chaque semaine (+467 % de taux de clic sponsors) et un premier concept d’appli. Plus d’1M de vues en une saison.",
        metricLabel: "taux de clic · 1M de vues",
      },
    },
    groundKicker: "Boîte à outils",
    groundTitle: "Au-delà des études de cas",
    capabilities: [
      "Cartographie des process",
      "Automatisation des workflows",
      "Assistants IA & LLM locaux",
      "Espaces Notion & passations",
      "Builds assistés par l’IA (Claude Code, Codex)",
      "Documentation bilingue FR/EN",
      "Expérience terrain clubs & événements",
    ],
    degree: "M2 International Sport Administration, Université de Lille. Mémoire : comment l’IA générative et le no-code peuvent rendre plus efficaces les associations sportives aux moyens limités. Le coaching, l’événementiel et la réserve de la Marine façonnent ma façon de préparer, de coordonner et de prendre mes responsabilités.",
    cards: [
      { label: "Royal Daring · Mai–juillet 2026", title: "Une passation pensée pour durer", body: "Un espace Notion pour les bénévoles et le prochain stagiaire : diagnostic de départ, charte éditoriale, 11 modèles de posts et un suivi des tâches, exporté en Markdown pour n’importe quel assistant IA." },
      { label: "Tournoi ASI · Décembre 2025", title: "500+ personnes, un seul briefing", body: "Un briefing participants bilingue FR/EN, et une nouvelle salle trouvée en 45 minutes quand le gymnase principal a été pris deux heures avant le début." },
    ],
  },
}

export const COPY: Record<Locale, Copy> = { en, fr }
