export const GAMES_MUX_PLAYBACK_ID = "rXy7eZY1FY6X020001gjC8gaX0233Ok901LMy00GavzkHr02Xs"
export const GAMES_BACKGROUND_POSTER = `https://image.mux.com/${GAMES_MUX_PLAYBACK_ID}/thumbnail.webp?time=0&width=1920`

export const GAMES = [
  {
    id: "overwatch",
    code: "OW",
    title: "Overwatch",
    category: "The competitive side",
    accent: "#f5aa53",
    stat: "TOP 20–200",
    statLabel: "Ranked over two years",
    text: "Overwatch is a big part of my competitive gaming story. I played in the Top 20–200 for two years, spending a lot of time in ranked matches and pushing my level.",
    note: "Two years of high-level ranked play.",
    tags: ["Competitive", "Team play", "Ranked"],
  },
  {
    id: "counter-strike",
    code: "CS2",
    title: "Counter-Strike",
    category: "One round at a time",
    accent: "#c8ff00",
    stat: "LEVEL 10",
    statLabel: "FACEIT",
    text: "Counter-Strike is another game I’ve put a lot into, reaching level 10 on FACEIT. The film playing behind this page brings together some of my own CS2 plays.",
    note: "My gameplay, in the background of this page.",
    tags: ["Competitive", "FACEIT", "CS2 highlights"],
  },
  {
    id: "osu",
    code: "OSU!",
    title: "osu!",
    category: "Rhythm under pressure",
    accent: "#ff78ad",
    stat: "7–8★ MAPS",
    statLabel: "Cleared, not mastered",
    text: "I’m not an osu! expert, but I play it regularly and can finish maps rated around 7–8 stars. The speed, repetition and precision make it a completely different kind of challenge.",
    note: "A quick, colourful test of rhythm and focus.",
    tags: ["Rhythm", "Aim", "7–8★ clears"],
  },
  {
    id: "minecraft",
    code: "MC",
    title: "Minecraft",
    category: "A city of my own",
    accent: "#a6c9a0",
    stat: "250+ HOURS",
    statLabel: "And still building",
    text: "I’m building a complete city by hand, using no mods beyond WorldEdit. Every building is unique, from the old city and canal district to the modern skyline.",
    note: "One long-term world, built district by district.",
    tags: ["Hand-built", "WorldEdit only", "One-off architecture"],
  },
] as const
